import '../globals.css';
import { Header } from '@/components';
import { PAGE_THEME } from '@/constants';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header theme={PAGE_THEME.dark} />
      <section className={'bg-t1-lightGray text-t1-black'}>{children}</section>
    </div>
  );
}
