/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
    _type: "sanity.imagePaletteSwatch"
    background?: string
    foreground?: string
    population?: number
    title?: string
}

export type SanityImagePalette = {
    _type: "sanity.imagePalette"
    darkMuted?: SanityImagePaletteSwatch
    lightVibrant?: SanityImagePaletteSwatch
    darkVibrant?: SanityImagePaletteSwatch
    vibrant?: SanityImagePaletteSwatch
    dominant?: SanityImagePaletteSwatch
    lightMuted?: SanityImagePaletteSwatch
    muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
    _type: "sanity.imageDimensions"
    height?: number
    width?: number
    aspectRatio?: number
}

export type SanityImageHotspot = {
    _type: "sanity.imageHotspot"
    x?: number
    y?: number
    height?: number
    width?: number
}

export type SanityImageCrop = {
    _type: "sanity.imageCrop"
    top?: number
    bottom?: number
    left?: number
    right?: number
}

export type SanityFileAsset = {
    _id: string
    _type: "sanity.fileAsset"
    _createdAt: string
    _updatedAt: string
    _rev: string
    originalFilename?: string
    label?: string
    title?: string
    description?: string
    altText?: string
    sha1hash?: string
    extension?: string
    mimeType?: string
    size?: number
    assetId?: string
    uploadId?: string
    path?: string
    url?: string
    source?: SanityAssetSourceData
}

export type SanityImageAsset = {
    _id: string
    _type: "sanity.imageAsset"
    _createdAt: string
    _updatedAt: string
    _rev: string
    originalFilename?: string
    label?: string
    title?: string
    description?: string
    altText?: string
    sha1hash?: string
    extension?: string
    mimeType?: string
    size?: number
    assetId?: string
    uploadId?: string
    path?: string
    url?: string
    metadata?: SanityImageMetadata
    source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
    _type: "sanity.imageMetadata"
    location?: Geopoint
    dimensions?: SanityImageDimensions
    palette?: SanityImagePalette
    lqip?: string
    blurHash?: string
    hasAlpha?: boolean
    isOpaque?: boolean
}

export type Geopoint = {
    _type: "geopoint"
    lat?: number
    lng?: number
    alt?: number
}

export type SanityAssetSourceData = {
    _type: "sanity.assetSourceData"
    name?: string
    id?: string
    url?: string
}

export type Blog = {
    _id: string
    _type: "blog"
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    slug?: Slug
    path?: string
    author?: {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "author"
    }
    positionTitle?: string
    descriptionShort?: string
    descriptionLong?: string
    body?: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
        }>
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
            href?: string
            _type: "link"
            _key: string
        }>
        level?: number
        _type: "block"
        _key: string
    }>
    heroImage?: string
    status?: "DRAFT" | "TO REVIEW" | "PUBLISHED" | "TESTING"
    length?: "IGNITE" | "BLOG"
    language?: "Deutsch" | "Englisch"
    tags?: Array<string>
    category?: "SOFTWARE ENGINEERING" | "METHODOLOGY" | "NEWS" | "CULTURE" | "EXPERIENCE"
    cta?: "CONTACT" | "CAREER" | "BLOG" | "NONE"
    date?: string
    toc?: boolean
}

export type Author = {
    _id: string
    _type: "author"
    _createdAt: string
    _updatedAt: string
    _rev: string
    name?: string
    position?: string
    profileImg?: string
    about?: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
        }>
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
            href?: string
            _type: "link"
            _key: string
        }>
        level?: number
        _type: "block"
        _key: string
    }>
}

export type Career = {
    _id: string
    _type: "career"
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    slug?: Slug
    path?: string
    description?: string
    location?: "Stuttgart"
    schedule?: "Vollzeit" | "Teilzeit"
    employmentType?: "Festanstellung" | "Praktikum" | "Werkstudent"
    division?: "Software Engineering" | "Agile Transformation" | "Operations" | "Marketing"
    tags?: Array<string>
    date?: string
    details?: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
        }>
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
            href?: string
            _type: "link"
            _key: string
        }>
        level?: number
        _type: "block"
        _key: string
    }>
    status?: "DRAFT" | "TO REVIEW" | "PUBLISHED"
}

export type Slug = {
    _type: "slug"
    current?: string
    source?: string
}

export type AllSanitySchemaTypes =
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageHotspot
    | SanityImageCrop
    | SanityFileAsset
    | SanityImageAsset
    | SanityImageMetadata
    | Geopoint
    | SanityAssetSourceData
    | Blog
    | Author
    | Career
    | Slug
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/sanity/queries.ts
// Variable: QUERY_ALL_CAREERS
// Query: *[_type == 'career' && defined(slug) && defined(slug.current)]
export type QUERY_ALL_CAREERSResult = Array<{
    _id: string
    _type: "career"
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    slug?: Slug
    path?: string
    description?: string
    location?: "Stuttgart"
    schedule?: "Teilzeit" | "Vollzeit"
    employmentType?: "Festanstellung" | "Praktikum" | "Werkstudent"
    division?: "Agile Transformation" | "Marketing" | "Operations" | "Software Engineering"
    tags?: Array<string>
    date?: string
    details?: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
        }>
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
            href?: string
            _type: "link"
            _key: string
        }>
        level?: number
        _type: "block"
        _key: string
    }>
    status?: "DRAFT" | "PUBLISHED" | "TO REVIEW"
}>
// Variable: QUERY_SPECIFIC_CAREER
// Query: *[_type == 'career' && slug.current == $slug][0]
export type QUERY_SPECIFIC_CAREERResult = {
    _id: string
    _type: "career"
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    slug?: Slug
    path?: string
    description?: string
    location?: "Stuttgart"
    schedule?: "Teilzeit" | "Vollzeit"
    employmentType?: "Festanstellung" | "Praktikum" | "Werkstudent"
    division?: "Agile Transformation" | "Marketing" | "Operations" | "Software Engineering"
    tags?: Array<string>
    date?: string
    details?: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
        }>
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
            href?: string
            _type: "link"
            _key: string
        }>
        level?: number
        _type: "block"
        _key: string
    }>
    status?: "DRAFT" | "PUBLISHED" | "TO REVIEW"
} | null
// Variable: QUERY_ALL_BLOGS
// Query: *[_type == 'blog' && defined(slug) && defined(slug.current)]{...,author->}
export type QUERY_ALL_BLOGSResult = Array<{
    _id: string
    _type: "blog"
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    slug?: Slug
    path?: string
    author: {
        _id: string
        _type: "author"
        _createdAt: string
        _updatedAt: string
        _rev: string
        name?: string
        position?: string
        profileImg?: string
        about?: Array<{
            children?: Array<{
                marks?: Array<string>
                text?: string
                _type: "span"
                _key: string
            }>
            style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
            listItem?: "bullet" | "number"
            markDefs?: Array<{
                href?: string
                _type: "link"
                _key: string
            }>
            level?: number
            _type: "block"
            _key: string
        }>
    } | null
    positionTitle?: string
    descriptionShort?: string
    descriptionLong?: string
    body?: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
        }>
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
            href?: string
            _type: "link"
            _key: string
        }>
        level?: number
        _type: "block"
        _key: string
    }>
    heroImage?: string
    status?: "DRAFT" | "PUBLISHED" | "TESTING" | "TO REVIEW"
    length?: "BLOG" | "IGNITE"
    language?: "Deutsch" | "Englisch"
    tags?: Array<string>
    category?: "CULTURE" | "EXPERIENCE" | "METHODOLOGY" | "NEWS" | "SOFTWARE ENGINEERING"
    cta?: "BLOG" | "CAREER" | "CONTACT" | "NONE"
    date?: string
    toc?: boolean
}>
// Variable: QUERY_SPECIFIC_BLOG
// Query: *[_type == 'blog' && slug.current == $slug][0]{...,author->}
export type QUERY_SPECIFIC_BLOGResult = {
    _id: string
    _type: "blog"
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    slug?: Slug
    path?: string
    author: {
        _id: string
        _type: "author"
        _createdAt: string
        _updatedAt: string
        _rev: string
        name?: string
        position?: string
        profileImg?: string
        about?: Array<{
            children?: Array<{
                marks?: Array<string>
                text?: string
                _type: "span"
                _key: string
            }>
            style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
            listItem?: "bullet" | "number"
            markDefs?: Array<{
                href?: string
                _type: "link"
                _key: string
            }>
            level?: number
            _type: "block"
            _key: string
        }>
    } | null
    positionTitle?: string
    descriptionShort?: string
    descriptionLong?: string
    body?: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
        }>
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
            href?: string
            _type: "link"
            _key: string
        }>
        level?: number
        _type: "block"
        _key: string
    }>
    heroImage?: string
    status?: "DRAFT" | "PUBLISHED" | "TESTING" | "TO REVIEW"
    length?: "BLOG" | "IGNITE"
    language?: "Deutsch" | "Englisch"
    tags?: Array<string>
    category?: "CULTURE" | "EXPERIENCE" | "METHODOLOGY" | "NEWS" | "SOFTWARE ENGINEERING"
    cta?: "BLOG" | "CAREER" | "CONTACT" | "NONE"
    date?: string
    toc?: boolean
} | null

// Source: ./src/app/career/page.tsx
// Variable: ALL_CAREER_QUERY
// Query: *[_type == "career" && !(division in ["", "null"])]
export type ALL_CAREER_QUERYResult = Array<{
    _id: string
    _type: "career"
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    slug?: Slug
    path?: string
    description?: string
    location?: "Stuttgart"
    schedule?: "Teilzeit" | "Vollzeit"
    employmentType?: "Festanstellung" | "Praktikum" | "Werkstudent"
    division?: "Agile Transformation" | "Marketing" | "Operations" | "Software Engineering"
    tags?: Array<string>
    date?: string
    details?: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
        }>
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
            href?: string
            _type: "link"
            _key: string
        }>
        level?: number
        _type: "block"
        _key: string
    }>
    status?: "DRAFT" | "PUBLISHED" | "TO REVIEW"
}>

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
    interface SanityQueries {
        "*[_type == 'career' && defined(slug) && defined(slug.current)]": QUERY_ALL_CAREERSResult
        "*[_type == 'career' && slug.current == $slug][0]": QUERY_SPECIFIC_CAREERResult
        "*[_type == 'blog' && defined(slug) && defined(slug.current)]{...,author->}": QUERY_ALL_BLOGSResult
        "*[_type == 'blog' && slug.current == $slug][0]{...,author->}": QUERY_SPECIFIC_BLOGResult
        '*[_type == "career" && !(division in ["", "null"])]': ALL_CAREER_QUERYResult
    }
}
