name: Pull Request

on:
    pull_request:
        branches:
            - main

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
            - name: Install dependencies
              uses: pnpm/action-setup@v4
              with:
                  version: latest
                  run_install: true
            - name: Run build
              env:
                  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
                  NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
              run: pnpm build
